language: node_js

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

cache:
  directories:
    - "frontend/node_modules"
    - "backend/node_modules"

node_js:
  - "node"

script:
  - cd frontend
  - npm install
  - npm run build
  - npm test
  - cd ../backend
  - npm install
  - npm test