version: '3'

services:
  server:
    build: ./server
    container_name: server
    environment:
      - TZ=America/Montreal
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www
      - ./server/static:/var/static

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    environment:
      - TZ=America/Montreal
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    environment:
      - TZ=America/Montreal
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/usr/src/app
