FROM nginx:1.13.0

RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/
RUN rm /etc/nginx/conf.d/default.conf
COPY app.conf.prod /etc/nginx/conf.d/app.conf

COPY build /var/www/
COPY static /var/static/
